In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("./final.csv")
df.head(5)

,Name,Attendance (%),Study Hours/Week,Previous Score,Extracurricular Activities,Final Score
0,Jane Smith,68.73,15.44,83.71,Low,65.07
1,Chris Jones,97.54,13.50,67.65,High,56.83
2,Emily Williams,86.60,15.46,71.73,Low,61.53
3,Jane Moore,79.93,5.06,67.09,High,56.21
4,Jane Taylor,57.80,13.90,50.74,High,37.17

In [4]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.head(5)

,name,attendance_(%),study_hours/week,previous_score,extracurricular_activities,final_score
0,Jane Smith,68.73,15.44,83.71,Low,65.07
1,Chris Jones,97.54,13.50,67.65,High,56.83
2,Emily Williams,86.60,15.46,71.73,Low,61.53
3,Jane Moore,79.93,5.06,67.09,High,56.21
4,Jane Taylor,57.80,13.90,50.74,High,37.17

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   name                        324 non-null    object
 1   attendance_(%)              324 non-null    float64
 2   study_hours/week            324 non-null    float64
 3   previous_score              324 non-null    float64
 4   extracurricular_activities  324 non-null    object
 5   final_score                 324 non-null    float64
dtypes: float64(4), object(2)
memory usage: 15.3+ KB

In [8]:
print(df.isnull().sum())

name                          0
attendance_(%)                0
study_hours/week              0
previous_score                0
extracurricular_activities    0
final_score                   0
dtype: int64

In [13]:
label_encoder = LabelEncoder()
df['extracurricular_activities'] = label_encoder.fit_transform(df['extracurricular_activities'])
df.head(5)

,name,attendance_(%),study_hours/week,previous_score,extracurricular_activities,final_score
0,Jane Smith,68.73,15.44,83.71,1,65.07
1,Chris Jones,97.54,13.50,67.65,0,56.83
2,Emily Williams,86.60,15.46,71.73,1,61.53
3,Jane Moore,79.93,5.06,67.09,0,56.21
4,Jane Taylor,57.80,13.90,50.74,0,37.17